spring.application.name=ScalableDistributedSystems
server.port=8080

key-value.mode=persistent

spring.datasource.left.url=jdbc:postgresql://localhost:5433/postgres
spring.datasource.left.username=postgres
spring.datasource.left.password=postgres

spring.datasource.right.url=jdbc:postgresql://localhost:5434/postgres
spring.datasource.right.username=postgres
spring.datasource.right.password=postgres

management.endpoints.web.exposure.include=health,prometheus
management.prometheus.metrics.export.enabled=true
management.metrics.distribution.percentiles-histogram.http.server.requests=true
